# Generated by Django 5.2.5 on 2025-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cuit_cuil',
            new_name='cuit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
