# Generated by Django 5.2.5 on 2025-08-25 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_cuit_cuil_client_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.local'),
        ),
    ]
