# Generated by Django 5.2.5 on 2025-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
    ]
