# Generated by Django 5.2.5 on 2025-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_manufactured',
            field=models.BooleanField(default=False),
        ),
    ]
