# Generated by Django 5.2.5 on 2025-08-27 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_is_manufactured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='product_design',
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='designs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'svg', 'cad'])])),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('patterns', models.TextField(blank=True, null=True)),
                ('processes', models.ManyToManyField(blank=True, related_name='designs', to='core.process')),
                ('raw_materials', models.ManyToManyField(blank=True, related_name='designs', to='core.rawmaterial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ordernote',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to='core.design'),
        ),
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.design'),
        ),
    ]
