# Generated by Django 5.2.5 on 2025-08-28 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_productionorder_product_design_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='design',
            name='patterns',
        ),
        migrations.RemoveField(
            model_name='design',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='design',
            name='raw_materials',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='design',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='local',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='ordernote',
            name='sale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_note', to='core.sale'),
        ),
        migrations.AddField(
            model_name='process',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo asociado a la ejecución de este proceso.', max_digits=10),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.design'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo calculado del diseño al momento de cotizar.', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.design'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo por unidad de medida.', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='related_quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quotation'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de Venta al Público (Valor).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Enviada', 'Enviada'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Borrador', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Valor de venta unitario ofrecido.', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'tenant')},
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='core.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.deliverynote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.design')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
