# Generated by Django 5.2.5 on 2025-08-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_design_dimensions_remove_design_patterns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad de materia prima necesaria para el diseño.', max_digits=10)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.design')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('design', 'raw_material', 'tenant')},
            },
        ),
        migrations.AddField(
            model_name='design',
            name='raw_materials',
            field=models.ManyToManyField(related_name='designs', through='core.DesignMaterial', to='core.rawmaterial'),
        ),
        migrations.CreateModel(
            name='DesignProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Orden secuencial del proceso en la fabricación.')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.design')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('design', 'process', 'tenant')},
            },
        ),
        migrations.AddField(
            model_name='design',
            name='processes',
            field=models.ManyToManyField(related_name='designs', through='core.DesignProcess', to='core.process'),
        ),
    ]
