# Generated by Django 5.2.5 on 2025-08-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_designmaterial_design_raw_materials_designprocess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernote',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_note', to='core.sale'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.design'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.design'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
    ]
