# Generated by Django 5.2.5 on 2025-08-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rawmaterial_supplier'),
    ]

    operations = [
    ]
