# Generated by Django 5.2.5 on 2025-08-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20250828_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='applies_to_indumentaria',
            field=models.BooleanField(default=False, help_text='Indica si este proceso aplica a productos de tipo Indumentaria.'),
        ),
        migrations.AddField(
            model_name='process',
            name='applies_to_medias',
            field=models.BooleanField(default=False, help_text='Indica si este proceso aplica a productos de tipo Medias.'),
        ),
    ]
