# Generated by Django 5.2.5 on 2025-08-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_product_stock_design_calculated_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
