# Generated by Django 5.2.5 on 2025-09-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_supplier_account_number_supplier_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issuer', models.CharField(max_length=255)),
                ('is_own', models.BooleanField(default=False)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.DateField()),
                ('receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('received_from', models.CharField(blank=True, max_length=255, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Cargado', 'Cargado'), ('Entregado', 'Entregado'), ('Rechazado', 'Rechazado'), ('Cobrado', 'Cobrado'), ('Anulado', 'Anulado')], default='Cargado', max_length=50)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
