# Generated by Django 5.2.5 on 2025-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
