# Generated by Django 5.2.5 on 2025-09-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rawmaterial_brand_rawmaterial_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrimaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brands', models.ManyToManyField(blank=True, to='core.brand')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='core.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='core.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('raw_material', 'supplier', 'tenant')},
            },
        ),
    ]
