# Generated by Django 5.2.5 on 2025-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_rawmaterial_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprimaproveedor',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
