# Generated by Django 5.2.5 on 2025-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_pedidomaterial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmaterial',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo unitario de la materia prima en el momento del diseño.', max_digits=10),
        ),
    ]
