# Generated by Django 5.2.5 on 2025-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_designmaterial_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='designprocess',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo del proceso para este diseño específico. Se puede sobreescribir el costo por defecto del proceso.', max_digits=10),
        ),
    ]
