# Generated by Django 5.2.5 on 2025-09-10 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_designprocess_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='design_file',
        ),
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='designs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='core.design')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
