# Generated by Django 5.2.5 on 2025-09-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_product_waste_product_weight_productfile'),
    ]

    operations = [
    ]
