# Generated by Django 5.2.5 on 2025-09-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_client_city_client_details_client_iva_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
