# Generated by Django 5.2.5 on 2025-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
