# Generated by Django 4.2.5 on 2025-09-11 16:09

from django.db import migrations

def generate_quotation_ids(apps, schema_editor):
    Quotation = apps.get_model('core', 'Quotation')
    for quotation in Quotation.objects.all():
        quotation.quotation_id = f"PRE-{quotation.id:03d}"
        quotation.save(update_fields=['quotation_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_quotation_quotation_id'),
    ]

    operations = [
        migrations.RunPython(generate_quotation_ids, reverse_code=migrations.RunPython.noop),
    ]