# Generated by Django 5.2.5 on 2025-09-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20250911_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='design',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
