# Generated by Django 5.2.5 on 2025-09-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_quotation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='design',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
