# Generated by Django 5.2.5 on 2025-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_quotationitem_color_quotationitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernote',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Produccion', 'En Producción'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50),
        ),
    ]
