# Generated by Django 5.2.5 on 2025-09-15 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_ordernote_shipping_method_ordernote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='design',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='size',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductionOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='production_orders/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.productionorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('customizations', models.JSONField(blank=True, default=dict, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.productionorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
