# Generated by Django 5.2.5 on 2025-09-17 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_productionorder_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
