# Generated by Django 5.2.5 on 2025-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_productionorder_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderitem',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
