# Generated by Django 5.2.5 on 2025-09-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_productionorderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='Producto base usado como plantilla para talles y colores.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='customization_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detalles de personalización como tipo de escudo, tela, cuello, etc.'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='detalle_equipo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='equipo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productionorderfile',
            name='file_type',
            field=models.CharField(choices=[('escudo', 'Escudo'), ('sponsor', 'Sponsor'), ('template', 'Template'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='core.ordernote'),
        ),
    ]
