# Generated by Django 5.2.5 on 2025-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_productionorder_base_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
