# Generated by Django 5.2.5 on 2025-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_productionorder_colors_productionorder_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='colors',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='specifications',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='colors',
            field=models.ManyToManyField(blank=True, to='core.color'),
        ),
    ]
