# Generated by Django 5.2.5 on 2025-09-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_productionorder_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmaterial',
            name='process',
            field=models.ForeignKey(blank=True, help_text='Proceso en el que se consume este material.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.designprocess'),
        ),
    ]
