# Generated by Django 5.2.5 on 2025-09-25 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_designmaterial_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcostrule',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Banco asociado a esta regla, si aplica.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bank'),
        ),
    ]
