# Generated by Django 5.2.5 on 2025-09-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_financialcostrule_bank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialcostrule',
            unique_together={('payment_method', 'bank', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='financialcostrule',
            name='name',
        ),
    ]
