# Generated by Django 5.2.5 on 2025-09-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_financialcostrule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprimaproveedor',
            name='brands',
        ),
        migrations.AddField(
            model_name='materiaprimaproveedor',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand'),
        ),
    ]
