# Generated by Django 5.2.5 on 2025-09-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_materiaprimaproveedor_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial'),
        ),
    ]
