# Generated by Django 5.2.5 on 2025-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_purchaseorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Comprada por Pagar', 'Comprada por Pagar'), ('Pagada', 'Pagada')], default='Pendiente', max_length=50),
        ),
    ]
