# Generated by Django 5.2.5 on 2025-09-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_payment_invoice_payment_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Comprada por Pagar', 'Comprada por Pagar'), ('Pagada', 'Pagada'), ('Pago Parcial', 'Pago Parcial'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50),
        ),
    ]
