# Generated by Django 5.2.5 on 2025-09-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_productionorder_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.size'),
        ),
    ]
