# Generated by Django 5.2.5 on 2025-10-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_warehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materiaprimaproveedor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materiaprimaproveedor',
            name='local',
            field=models.ForeignKey(blank=True, help_text='Almacén donde se encuentra este stock de materia prima', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.local'),
        ),
        migrations.AlterUniqueTogether(
            name='materiaprimaproveedor',
            unique_together={('raw_material', 'supplier', 'local', 'tenant')},
        ),
    ]
