# Generated by Django 5.0.6 on 2025-10-02 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_materiaprimaproveedor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materiaprimaproveedor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='materiaprimaproveedor',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='core.warehouse'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='local',
        ),
        migrations.RemoveField(
            model_name='materiaprimaproveedor',
            name='local',
        ),
    ]
