# Generated by Django 5.0.6 on 2025-10-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_warehouse_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='materiaprimaproveedor',
            unique_together={('raw_material', 'supplier', 'warehouse', 'tenant')},
        ),
    ]
