# Generated by Django 5.0.6 on 2025-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_update_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_default_for_finished_products',
            field=models.BooleanField(default=False),
        ),
    ]
