# Generated by Django 5.0.6 on 2025-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_default_warehouse_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='iva_condition',
            field=models.CharField(blank=True, choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('No Responsable', 'No Responsable'), ('Exento', 'Exento'), ('Responsable Monotributo', 'Responsable Monotributo'), ('Monotributista Social', 'Monotributista Social')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='iva_condition',
            field=models.CharField(blank=True, choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('No Responsable', 'No Responsable'), ('Exento', 'Exento'), ('Responsable Monotributo', 'Responsable Monotributo'), ('Monotributista Social', 'Monotributista Social')], max_length=50, null=True),
        ),
    ]
