# Generated by Django 5.0.6 on 2025-10-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_client_iva_condition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materiaprimaproveedor',
            unique_together={('raw_material', 'warehouse', 'tenant')},
        ),
        migrations.AlterField(
            model_name='materiaprimaproveedor',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_primas', to='core.supplier'),
        ),
    ]
