# Generated by Django 5.0.6 on 2025-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_materiaprimaproveedor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad de materia prima necesaria para el diseño.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='customization_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detalles de personalización como tipo de escudo, tela, cuello, etc.', null=True),
        ),
    ]
