# Generated by Django 5.0.6 on 2025-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_designmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderitem',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
