# Generated by Django 5.0.6 on 2025-10-13 02:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_productionorderitem_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='status',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente para remitos de venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='destino',
            field=models.ForeignKey(blank=True, help_text='Almacén de destino (para remitos internos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos_entrada', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha del remito'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='origen',
            field=models.ForeignKey(help_text='Almacén de origen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remitos_salida', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='tipo',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Interno', 'Interno')], default='Venta', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='venta_asociada',
            field=models.ForeignKey(blank=True, help_text='Venta asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos', to='core.sale'),
        ),
    ]
