# Generated by Django 5.0.6 on 2025-10-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercializadora', '0001_initial'),
        ('core', '0068_remove_employee_local_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_default_for_finished_products',
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='commercial_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercializadora.commercialproduct'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='local',
            field=models.ForeignKey(blank=True, help_text='Local al que pertenece (si no es central)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.local'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('central', 'Almacén Central'), ('local_storage', 'Almacén de Local'), ('local_exhibition', 'Exhibición de Local')], default='central', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='Dirección no especificada', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cuil',
            field=models.CharField(default='00-00000000-0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='Nombre no especificado', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Apellido no especificado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='deliverynoteitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('commercial_product__isnull', True), ('product__isnull', False)), models.Q(('commercial_product__isnull', False), ('product__isnull', True)), _connector='OR'), name='core_deliverynoteitem_uno_solo_producto'),
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table=None,
        ),
    ]
